// voting-card/src/components/voting-card.component.ts
import { OnInit } from '@angular/core';
import { Component, Input } from '@angular/core'

@Component({
  selector: 'card',
  template: `
    <div class="votingCard">
        <h1>{{title}}</h1>
        <div *ngIf="state === 'open'; else showResult" >  
            <br/>
            <booth 
                [options]="boothOptions"
                (select)="onSelect($event)"
            >
            </booth>
        </div>

        <ng-template #showResult>
            <result [votes]="votes" ></result>
        </ng-template>
    </div>
  `,
  styles: [
    `
        .votingCard{
            padding: 10px;
            border-radius: 5px;
            border: 1px solid #000;
            background-color: cornflowerblue;
        }
    `
  ]
})

export class VotingCardComponent implements OnInit {
    @Input() title: string | undefined
    @Input() state: string | undefined
    @Input() votes: { text: string; count: number; }[] = []
    boothOptions = ['']

    onSelect(i: any){
        this.votes[i].count++;
        this.state = "closed";
    }    

    ngOnInit() {
        this.boothOptions = this.votes.map(option => (option.text));
    }
}

// voting-card/src/components/voting-card.vue
<template>
    <div class="votingCard">
        <h1>
            {{ title }}
        </h1>

        <div id="booth" v-if="mutState === 'open'">
            <Booth 
                :options="boothOptions" 
                @select="select"    
            />
        </div>
        <div v-else-if="mutState === 'closed'">
            <Result :votes="votes"></Result>
        </div>
        <div v-else>
            <h1>Not Found</h1>
        </div>
    </div>
</template>

<script>
    import Booth from './voting-booth.vue'
    import Result from './voting-result.vue'

    export default {
        props: ['title', 'state', 'votes'],
        watch: {
            state: function(){
                this.mutState = this.state
            }
        },
        data: () => ({
            boothOptions: [],
            mutState: ''
        }),
        components: {
            Booth, Result
        },
        methods: {
            select(optionIndex){
                this.mutState = "closed";
                this.votes[optionIndex].count++;
            }
        },
        created: function (){
            this.boothOptions = this.votes.map(option => (option.option));
            this.mutState = this.state;
        }
    }
</script>

<style>
    .votingCard{
        padding: 10px;
        border-radius: 5px;
        border: 1px solid #000;
        background-color: cornflowerblue;
    }
</style>
